version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Amsterdam"

    # Limit noise
    open-pull-requests-limit: 10

    # Conventional‑commit style PR titles/commits
    commit-message:
      prefix: "chore(deps)"
      include: "scope"   # adds (deps) or (deps-dev)

    # Optional labels for the PRs (override defaults)
    labels:
      - "dependencies"

    # Group related updates into fewer PRs
    groups:
      maven-plugins:
        dependency-type: "development"     # only plugin/build deps
        patterns:
          - "org.apache.maven.plugins:*"
          - "org.sonatype.central:central-publishing-maven-plugin"
      javafx:
        patterns:
          - "org.openjfx:*"
