name: Deployment

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
      CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Writes ~/.m2/settings.xml with <server id="central"> that references ${env.CENTRAL_USERNAME}/${env.CENTRAL_PASSWORD}
      - name: Set up JDK 24 (Temurin) + Central credentials
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "24"
          cache: maven
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD

      - name: Make Maven Wrapper executable (fix line endings + chmod)
        run: |
          sed -i 's/\r$//' mvnw
          chmod +x mvnw

      - name: Import GPG private key (for maven-gpg-plugin) and warm up agent
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE:  ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent

          # Import key
          echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --import

          # Preload passphrase into gpg-agent by doing a dummy sign once
          # (this avoids passing any passphrase property to Maven)
          echo "warmup" > /tmp/warmup.txt
          echo "$GPG_PASSPHRASE" | \
            gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 \
                --local-user 0x09ADA3A346567D4DBCC95D5761998A60B3A5A289 \
                --output /tmp/warmup.sig --sign /tmp/warmup.txt
          rm -f /tmp/warmup.txt /tmp/warmup.sig

          # Show key (no secrets printed)
          gpg --list-secret-keys --keyid-format LONG

      - name: (Optional) Show Effective Settings (masks passwords)
        run: ./mvnw -V -B -ntp help:effective-settings -DshowPasswords=false

      - name: Build & Deploy to Maven Central
        run: |
          ./mvnw -V -B -ntp clean deploy