name: Deployment

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # JDK + credentials for Sonatype Central; writes ~/.m2/settings.xml with <server id="central">
      - name: Set up JDK 24 (Temurin) + Central credentials
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "24"
          cache: maven
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}

      - name: Make Maven Wrapper executable (fix line endings + chmod)
        run: |
          sed -i 's/\r$//' mvnw
          chmod +x mvnw

      - name: Import GPG private key (for maven-gpg-plugin)
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --import
          # non-interactive pinentry
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent
          # optional visibility (no secrets printed)
          gpg --list-secret-keys --keyid-format LONG

      - name: Build & Deploy to Maven Central
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          ./mvnw -V -B -ntp clean deploy