name: Deployment

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # lets you read the tag/commit info if you ever need it

      - name: Set up JDK 24 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "24"
          cache: maven

      - name: Make Maven Wrapper executable (LF line endings + chmod)
        run: |
          sed -i 's/\r$//' mvnw
          chmod +x mvnw

      # Import GPG private key (for maven-gpg-plugin signing)
      - name: Import GPG private key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          # good practice for non-interactive pinentry
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent

      # Provide Sonatype Central credentials to Maven (id must match <publishingServerId>central</publishingServerId> in pom.xml)
      - name: Configure Maven settings.xml (Sonatype Central)
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'XML'
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>central</id>
                <username>${env.CENTRAL_USERNAME}</username>
                <password>${env.CENTRAL_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          XML

      - name: Show Effective Settings (sanity check; masks secrets)
        run: ./mvnw -V -B -ntp help:effective-settings -DshowPasswords=false

      - name: Deploy to Maven Central - Sonatype
        env:
          # gpg passphrase supplied via system property so you don't need to hardcode it in pom.xml
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          # Helps pinentry in headless CI
          GPG_TTY: ${{ env.GITHUB_WORKSPACE }}
        run: |
          ./mvnw -V -B -ntp clean deploy \
            -Dgpg.passphrase="${GPG_PASSPHRASE}"